apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdb-deployment
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 100%
  #  strategy:
  #    type: Recreate
  selector:
    matchLabels:
      app: productdb
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
        - name: productdb
          image: mysql:8.0
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: productdb-config
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              value: dbpassword11
          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
            - name: productdb-config
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance
      volumes:
#        - name: mysql-persistent-storage
#          persistentVolumeClaim:
#            claimName: ebs-mysql-pv-claim
        - name: productdb-config
          configMap:
            name: productdb-config