spring:
  application:
    name: product-service

  datasource:
#    url: jdbc:mysql://localhost:3302/productdb
    url: ${PRODUCT_DB_URL}
    username: root
    password: dbadmin

  jpa:
    hibernate:
#      ddl-auto: none
          ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev
          issuer-uri: ${KEYCLOAK_SERVICE_ISSUER_URI}
server:
#  port: 5002
  port: ${PRODUCT_SERVICE_PORT}
