spring:
  application:
    name: notification-service

#  datasource:
#    url: jdbc:mysql://localhost:3301/notification-service
##    url: ${NOTIFICATION_DB_URL}
#    username: root
#    password: dbadmin
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
#
#    show-sql: true
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
#
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: false

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev

server:
#  port: ${NOTIFICATION_SERVICE_PORT}
  port: 5006