---
apiVersion: v1
kind: Service
metadata:
  name: credit-service
spec:
  type: NodePort
  selector:
    app: credit
  ports:
    - protocol: TCP
      port: 5507
      nodePort: 30507
      targetPort: 5507