---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-deployment
  labels:
    app: credit
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: credit
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
      - name: credit-service
        image: credit:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: http
            containerPort: 5507
        envFrom:
          - configMapRef:
              name: common-config
      terminationGracePeriodSeconds: 1
