spring:
  application:
    name: account-service

  datasource:
#    url: jdbc:mysql://localhost:3301/accountdb
    url: ${ACCOUNT_DB_URL}
    username: root
    password: dbadmin

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev
          issuer-uri: ${KEYCLOAK_SERVICE_ISSUER_URI}
#          jwk-set-uri: http://sa-keycloak:9090/realms/sa-mini-project1-realm-prod/protocol/openid-connect/certs
          jwk-set-uri: ${KEYCLOAK_SERVICE_JWK_SET_URI}


server:
#  port: 5001
  port: ${ACCOUNT_SERVICE_PORT}