spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3308/account-service
#    url: ${ACCOUNT_DB_URL}
    username: root
    password: dbadmin

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev
          jwk-set-uri: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: sa-mini-project2
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev
            user-name-attribute: preferred_username

keycloak:
  client-id: sa-mini-project2
  secret: Yvhd7uSP0krdOb5fanvH1DWKIKsUyZqT
  auth-url: http://localhost:8000/auth/realms/sa-mini-project2-realm-dev/protocol/openid-connect/token

server:
#  port: ${ACCOUNT_SERVICE_PORT}
  port: 5001