---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account-service
        image: account:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: http
            containerPort: 5501
        envFrom:
          - configMapRef:
              name: account-config
      terminationGracePeriodSeconds: 1
