---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account-service
          image: thiepha/account:0.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 5501
          envFrom:
            - configMapRef:
                name: common-config
      terminationGracePeriodSeconds: 1
