---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: NodePort
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 5501
      nodePort: 30501
      targetPort: 5501