spring:
  application:
    name: order

  datasource:
#    url: jdbc:mysql://localhost:5001/orderdb
    url: ${ORDER_DB_URL}
#    url: jdbc:mysql://shoppingdb:3306/orderdb
    username: root
    password: dbadmin


  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true

server:
  port: ${ORDER_SERVICE_PORT}