---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-service
        image: order:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: http
            containerPort: 5503
        envFrom:
          - configMapRef:
              name: order-config
      terminationGracePeriodSeconds: 1
