spring:
  application:
    name: shipping

  datasource:
#    url: jdbc:mysql://localhost:5005/creditdb
    url: ${SHIPPING_DB_URL}
#    url: jdbc:mysql://shoppingdb:3306/creditdb
    username: root
    password: dbadmin


  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true

server:
  port: ${SHIPPING_SERVICE_PORT}