---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 5502
      nodePort: 30502
      targetPort: 5502