---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: NodePort
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 5505
      nodePort: 30505
      targetPort: 5505