---
apiVersion: v1
kind: Service
metadata:
  name: paypal-service
spec:
  type: NodePort
  selector:
    app: paypal
  ports:
    - protocol: TCP
      port: 5508
      nodePort: 30508
      targetPort: 5508