---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  type: NodePort
  selector:
    app: bank
  ports:
    - protocol: TCP
      port: 5509
      nodePort: 30509
      targetPort: 5509