---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: bank
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank-service
        image: bank:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: http
            containerPort: 5509
        envFrom:
          - configMapRef:
              name: common-config
      terminationGracePeriodSeconds: 1
