apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountdb-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: accountdb
  template:
    metadata:
      labels:
        app: accountdb
    spec:
      containers:
        - name: accountdb
          image: mysql:8.0
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: common-config
#            - configMapRef:
#                name: accountdb-config
      terminationGracePeriodSeconds: 1